// This file is auto-generated by @hey-api/openapi-ts

export type Category = {
	name: string;
	description: string;
	id: number;
};

export type CreateCategory = {
	name: string;
	description: string;
};

export type CreateTask = {
	name: string;
	description: string;
	category_id: number;
	status: string;
};

export type HTTPValidationError = {
	detail?: Array<ValidationError>;
};

export type Task = {
	name: string;
	description: string;
	category_id: number;
	status: string;
	id: number;
};

export type UpdateCategory = {
	name?: string | null;
	description?: string | null;
};

export type UpdateTask = {
	name?: string | undefined;
	description?: string | undefined;
	category_id?: number | undefined;
	status?: string | undefined;
};

export type ValidationError = {
	loc: Array<string | number>;
	msg: string;
	type: string;
};

export type CategoriesReadCategoriesResponse = Array<Category>;

export type CategoriesCreateCategoryData = {
	requestBody: CreateCategory;
};

export type CategoriesCreateCategoryResponse = Category;

export type CategoriesReadCategoryData = {
	categoryId: number;
};

export type CategoriesReadCategoryResponse = Category;

export type CategoriesUpdateCategoryData = {
	categoryId: number;
	requestBody: UpdateCategory;
};

export type CategoriesUpdateCategoryResponse = Category;

export type CategoriesDeleteCategoryData = {
	categoryId: number;
};

export type CategoriesDeleteCategoryResponse = Category;

export type TasksReadTasksResponse = Array<Task>;

export type TasksCreateTaskData = {
	requestBody: CreateTask;
};

export type TasksCreateTaskResponse = Task;

export type TasksReadTaskData = {
	taskId: number;
};

export type TasksReadTaskResponse = Task;

export type TasksUpdateTaskData = {
	requestBody: UpdateTask;
	taskId: number;
};

export type TasksUpdateTaskResponse = Task;

export type TasksDeleteTaskData = {
	taskId: number;
};

export type TasksDeleteTaskResponse = Task;
