name: CD

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
            DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
            PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
            DOCKER_IMAGE_BACKEND: ${{ vars.DOCKER_IMAGE_BACKEND }}
            DOCKER_IMAGE_NGINX: ${{ vars.DOCKER_IMAGE_NGINX }}
            SSL_CERTIFICATE: /etc/letsencrypt/live/taskmaneger.zapto.org/fullchain.pem
            SSL_CERTIFICATE_KEY: /etc/letsencrypt/live/taskmaneger.zapto.org/privkey.pem
        steps:
            - name: Login to Docker Hub
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      docker login \
                      -u "${{ secrets.DOCKER_USERNAME }}" \
                      --password-stdin <<< "${{ secrets.DOCKERHUB_TOKEN }}"

            - name: Pull Latest Docker Images
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  envs: DOCKER_IMAGE_BACKEND, DOCKER_IMAGE_NGINX

                  script: |
                      cd /home/ec2-user/TasksManeger
                      docker compose -f docker-compose.yml pull

            - name: Stop and Remove Existing Containers
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /home/ec2-user/TasksManeger
                      docker compose down

            - name: Restart Services with Updated Images
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  envs: DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_NAME, DATABASE_PORT, PROJECT_NAME, DOCKER_IMAGE_BACKEND, DOCKER_IMAGE_NGINX, SSL_CERTIFICATE, SSL_CERTIFICATE_KEY
                  script: |
                      echo "Verifying environment variables:"
                      echo "PROJECT: ${PROJECT_NAME:-[NOT SET]}"
                      echo "DB: ${DATABASE_USERNAME:-[NOT SET]}@*****:${DATABASE_PORT:-[NOT SET]}/${DATABASE_NAME:-[NOT SET]}"
                      echo "IMAGES: Backend=${DOCKER_IMAGE_BACKEND:-[NOT SET]}, Nginx=${DOCKER_IMAGE_NGINX:-[NOT SET]}"
                      echo "SSL: Cert=${SSL_CERTIFICATE:+[SET]}, Key=${SSL_CERTIFICATE_KEY:+[SET]}"
                      echo "Secrets: DB_PWD=${DATABASE_PASSWORD:+[MASKED]}, SSL_CERT=${SSL_CERTIFICATE:+[MASKED]}, SSL_KEY=${SSL_CERTIFICATE_KEY:+[MASKED]}"
                      
                      cd /home/ec2-user/TasksManeger
                      docker compose -f docker-compose.yml up -d --remove-orphans
